
server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kgueats?autoReconnection=true&serverTimezone=UTC&characterEncoding=UTF-8
    username: sinb57
    password: qwe123!@#
    driver-class-name: com.mysql.cj.jdbc.Driver
#    initialization-mode: always


  jpa:
    database: mysql
    hibernate.ddl-auto: update
#    show-sql: true
#    properties.hibernate.format_sql: true
