
server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/kgueats
    username: sa
    password:
    driver-class-name: org.h2.Driver
#    initialization-mode: always


  jpa:
    database: h2
    hibernate.ddl-auto: update
#    show-sql: true
#    properties.hibernate.format_sql: true
